---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb
  namespace: home
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-646b5857-b8fe-4a1c-940b-f7ba2fead0c2
