---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-provisioner
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/disabled: "true"
spec:
  targetNamespace: kube-system
  path: ./kubernetes/apps/kube-system/local-path-provisioner/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
