---
apiVersion: v1
kind: Service
metadata:
  name: cabinetpiet
  namespace: cabinetpiet
  labels:
    app: cabinetpiet
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cabinetpiet
  type: ClusterIP
