---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: recyclarr
  namespace: flux-system
spec:
  path: ./kubernetes/apps/media/recyclarr/app
  prune: false
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
