apiVersion: v1
kind: Secret
metadata:
    name: app-arr-secret
    namespace: media
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:cZb6ETqaN6twn00oGgALC/83c93NbiDjmwD2OrTxDGY=,iv:zHMhKwPbTtwNn5sjEPYvMDt7/B3qQsPUynWdtFgH14E=,tag:92g0TKPYTkqLJnAQPmMHcg==,type:str]
    SONARR__API_KEY: ENC[AES256_GCM,data:hn03q0p+Va9Bi7bRTybY8rAl8dsoOiKtkMnpwWphyQo=,iv:Px4IQ7EHXrML7ZZ9XJs6aJ2pInkL2BfR90tlPBKAt3I=,tag:VcO4EX1+FJbKwBQ9CCZY2A==,type:str]
    PROWLARR__API_KEY: ENC[AES256_GCM,data:m8Cw/7qNO0zlM9i0O5O//L8Rie4Z6BqQJMlqv17Eh8I=,iv:GG8wqmXeXeg0HhJTKBWjzGnpr2Iy0l65sqvxcAXwutw=,tag:8jgcGLcvdGnlDfuJykMvUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gekefns4nyh2xrkwgll67yt232gl0gndkuq0xrvd8clsjt2gzeas2zryhg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRlZJTmZaM1ZGeEI1anNn
            cEw5R0FUUVY0VGVSNHlqWFpGOWYwWllmbG40CitEczhESkxYbFhiMG1HZ1AxeGpX
            Z2k4T3k2OGQrbWhibnBBcG9iMGd2cFkKLS0tIFVza1lETTN4cTRQRmVGSDk0RVIr
            YzYvS211UVFLT1JhSTFiVUoyTVkzdlEK0mwbART7YKlvGgtj9bVkigBVXjX530/G
            oEcOaNHAObpG7JaF8iuTGfI3fuUtXfce5J6CbbO7KwEVy3QL6ojRPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-11T07:06:32Z"
    mac: ENC[AES256_GCM,data:tYVvVBflYLFRGljjwHPYlMDIkiJbQWLGexbICrBh5EmktD+GW2R3RMpwgIUmZuwqVHTnPvotYyfdk/GNLqdWoJjSXjRrbS6SQj4ZgAFjkoe8AgbEa0mAlmoxyhWj1GAADL3qJjjPOcc7xvZlbPGwR2AcQrP5KqSC/Q6F4tk+Wug=,iv:trIy2xkr4sISm3JJVzSS2AIgcetzefZGF0E1leMw1Wo=,tag:6jBcjUmKrhEnBBhFjszMLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
