ansible_become_pass: ENC[AES256_GCM,data:qVKGfMmo8ZI=,iv:4UHLByycZCAkJL8vrvSGGwgZ21FSbQdyejsb+HWluxo=,tag:OjbVhwe7HIglRtoHmYYjxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gekefns4nyh2xrkwgll67yt232gl0gndkuq0xrvd8clsjt2gzeas2zryhg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkM2daZW50M2R2RmRLekNt
            bHRsYnlnd1lNN0lMS2VheUt3SnJCWEMxOG5rCmJWUlh6R2ExTSt6UlBzOE9UVzFo
            NzYwcVkrK1N4SEFCWUJ5Q0pwdFNOaFUKLS0tIFVneVE1SVcxZ2dCUWFaVmhjQldS
            QTNkY005cS9YYmZNY0lxWjRKOWpZaXcK1lu0jzbuFycMXh9sJaZn+zm/HwygVG27
            1zrAwUcPuB2zF259NpDasRr0ANWUXwNMgfiPr4FZBDul7pLauqVGXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T14:59:34Z"
    mac: ENC[AES256_GCM,data:JlEAkGPDYpkkm90tdXZ8RPi8vxRRihLDx/zWiSQ2M0c7LaB00+QRXP7fhpjfLx+MlBBwvCRe8H9f+rFhkJ68wup0D6ka2Kty+taU24QqEGna9oYJ16dKAwvEt02qfFGQKLraMeibYkKtc5tVinvmkvIKUi4FhWSOgCC3ARhuM/I=,iv:xqoWGJGqVRdci5Uioj+Q90djxMrN7SrYtMTjQeBI7pc=,tag:xABSU5tlkLbGSAFnf1LTXw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
