---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: amd-device-plugin
  namespace: flux-system
spec:
  interval: 15m
  url: https://rocm.github.io/k8s-device-plugin/
  timeout: 3m
