---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hajimari
spec:
  interval: 30m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    env:
      TZ: Europe/Paris
    hajimari:
      title: Apps
      darkTheme: lime
      lightTheme: paper
      alwaysTargetBlank: true
      defaultEnable: true
      namespaceSelector:
        any: true
      name: "おかえりなさい"
      defaultSearchProvider: DuckDuckGo
      showAppGroups: true
      customApps: []
        # - group: Home
        #   apps:
        #     - name: Home Assistant
        #       url: https://${SECRET_DOMAIN}/
        #       icon: mdi:home-automation
      showGlobalBookmarks: true
      globalBookmarks:
        # - name: Communicate
        #   bookmarks:
        #     - name: Discord
        #       url: "https://discord.com/login"
        #     - name: Telegram
        #       url: "https://web.telegram.org/z/"
        #     - name: Slack
        #       url: "https://slack.com/signin"
        - name: mail
          bookmarks:
            - name: Gmail
              url: "https://gmail.com"
            - name: Proton
              url: "https://mail.proton.me"
        - name: Media
          bookmarks:
            - name: Netflix
              url: "https://www.netflix.com/browse"
            - name: Disney+
              url: "https://www.disneyplus.com/login"
            - name: YouTube
              url: "https://youtube.com/feed/subscriptions"
            - name: Amazon Prime
              url: "https://www.primevideo.com"
            - name: Spotify
              url: "https://open.spotify.com/browse"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: hajimari.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 50m
        memory: 128M
