---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hajimari
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    env:
      TZ: Europe/Paris
    hajimari:
      title: Apps
      darkTheme: lime
      lightTheme: paper
      alwaysTargetBlank: true
      defaultEnable: true
      namespaceSelector:
        any: true
      name: "おかえりなさい"
      defaultSearchProvider: DuckDuckGo
      showAppGroups: true
      customApps:
        []
        # - group: Home
        #   apps:
        #     - name: Home Assistant
        #       url: https://${SECRET_DOMAIN}/
        #       icon: mdi:home-automation
      showGlobalBookmarks: true
      globalBookmarks:
        # - name: Communicate
        #   bookmarks:
        #     - name: Discord
        #       url: "https://discord.com/login"
        #     - name: Telegram
        #       url: "https://web.telegram.org/z/"
        #     - name: Slack
        #       url: "https://slack.com/signin"
        - name: mail
          bookmarks:
            - name: Gmail
              url: "https://gmail.com"
            - name: Proton
              url: "https://mail.proton.me"
        - name: Media
          bookmarks:
            - name: Netflix
              url: "https://www.netflix.com/browse"
            - name: Disney+
              url: "https://www.disneyplus.com/login"
            - name: YouTube
              url: "https://youtube.com/feed/subscriptions"
            - name: Amazon Prime
              url: "https://www.primevideo.com"
            - name: Spotify
              url: "https://open.spotify.com/browse"
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 50m
        memory: 128M
