---
apiVersion: v1
kind: Service
metadata:
  name: nas
  namespace: networking
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 5001
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nas
  namespace: networking
subsets:
  - addresses:
      - ip: 192.168.10.12
    ports:
      - port: 5001
