---
apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: networking
  labels:
    app: pihole
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pihole
  namespace: networking
  labels:
    app: pihole
subsets:
  - addresses:
      - ip: 192.168.42.2
    ports:
      - port: 80

