apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:dqVETy0Ub/1kftuZOcBtbdCykWIAjA6/,iv:41SxX6WE2CdB3XnkkdhT45CRLvGRiyB7vc+kCqZo/Og=,tag:pNaLEpQvQYdjbOdFMjF2VQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gekefns4nyh2xrkwgll67yt232gl0gndkuq0xrvd8clsjt2gzeas2zryhg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWHlYbFAzL0hJNmVlTmlH
            MWpEQnU1R2hNdnlGMUVPOTAweU9MVzlUelhzCjN2YUxSYmM2QWpGdlVTeDg2M1Ez
            L2NuTFlYeU41MVV4V0JMY0FwZy84cDAKLS0tIDd3Q2Qzakl5U0FoR3FZbUNxS2hp
            RTFYTWtnN1FzR0tMeHI3UXFXUHNBOHMKvZSbj7+fsxJbCBpD7Sp8WUIMSVxI8uY0
            LRyQgYhr6X5OCHUKo89/yCADfiiWWvMWkI+ckx1+xZnKJqgTIwqdhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T19:06:22Z"
    mac: ENC[AES256_GCM,data:OLRqw2XP7YbxXp9gFxqG8tRE1aS7xkXv24wEMFM+am4Lt4EgCTOXu4MI5ZrZc2g1OFMoOf1ep78n1vmuC0pJFyT/k1si1IJRdkY3cSOLMzKNbbU4vr6Wd8UiXnrVbDwKZ0m+FPOc9BRc7HJVjeLYCvgbXeL4zvOmWiwKkmzNNic=,iv:xbKg5Rmh+6mNk1ZUDgI/2TOcQon7ZDVhz8bSQy62Q+I=,tag:ASF+vS5pP2xFLfwJ+KGPuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
