---
# https://docs.cilium.io/en/latest/network/l2-announcements
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
spec:
  loadBalancerIPs: true
  # NOTE: interfaces might need to be set if you have more than one active NIC on your hosts
  # interfaces:
  #   - ^eno[0-9]+
  #   - ^eth[0-9]+
  interfaces:
    - ^enp.*
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: l2-pool
spec:
  allowFirstLastIPs: "Yes"
  blocks:
    - cidr: "${CILIUM_POOL_CIDR}"
# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumbgpadvertisement_v2alpha1.json
# apiVersion: cilium.io/v2alpha1
# kind: CiliumBGPAdvertisement
# metadata:
#   name: l3-bgp-advertisement
#   labels:
#     advertise: bgp
# spec:
#   advertisements:
#     - advertisementType: Service
#       service:
#         addresses: ["LoadBalancerIP"]
#       selector:
#         matchExpressions:
#           - { key: somekey, operator: NotIn, values: ["never-used-value"] }
# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumbgppeerconfig_v2alpha1.json
# apiVersion: cilium.io/v2alpha1
# kind: CiliumBGPPeerConfig
# metadata:
#   name: l3-bgp-peer-config
# spec:
#   families:
#     - afi: ipv4
#       safi: unicast
#       advertisements:
#         matchLabels:
#           advertise: bgp
# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumbgpclusterconfig_v2alpha1.json
# apiVersion: cilium.io/v2alpha1
# kind: CiliumBGPClusterConfig
# metadata:
#   name: l3-bgp-cluster-config
# spec:
#   nodeSelector:
#     matchLabels:
#       kubernetes.io/os: linux
#   bgpInstances:
#     - name: cilium
#       localASN: 64520
#       peers:
#         - name: ccr2004
#           peerASN: 64520
#           peerAddress: 192.168.42.1
#           peerConfigRef:
#             name: l3-bgp-peer-config
