---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-unify
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-4a5f70ef-c200-42d1-9172-4055254d9133
