---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recyclarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-d59d7beb-8293-41dd-a167-4da55f758544

