apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:p6dTSBtFCxPVlid2xROFVQ==,iv:pWtlAKzWV2Kg0MsIqnVpUEo3Avv7Mkqk+XdP53X7J6M=,tag:aSCvoUNeQI8AfxN2YcAj5Q==,type:str]
    admin-user: ENC[AES256_GCM,data:COUhoPc=,iv:3dDSOEnioZR03j3z9sFHWJYzvDoQJf4srDVudVvihqw=,tag:LGTuz/knXWvtU2BjLzzC4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gekefns4nyh2xrkwgll67yt232gl0gndkuq0xrvd8clsjt2gzeas2zryhg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZit4dytHdVpMbWtZVm9o
            RElIRUhlUDI0VjlUbERlaXRRbGpyaGdEbXdzCkVibkZtN2VFQmx5N2JHemJpemM3
            OFFXb3NaV0hzRWNGbmtqL2xyZUJxNWcKLS0tIHYxd3ZlT3VJZ1B2UW9WdEdoYWpm
            Sjk0ajFXVTc0aXYxdnRqR1p4SnlRWkkKI05wd5FvZWiCjgJwrYlVAlKKfHEn5rjG
            laLIbsLxwGRbe2JMyErsLAB47hYf/pd1W98rOR6/TuMOU13L2IBlTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T19:06:29Z"
    mac: ENC[AES256_GCM,data:dW4GioEDSM9UwTScNfOCsJiPecrD7TUSN3qRlajR9z69h5QrBgntzD4mhsymMGfIYs5DJ39rOSlDiVXxboOHEThVgSlntQyDFeRHRO9d8AQpsX1xtjyoibg88IPW2i3yN4O0gjTAZNpHcxd/1EY2NMGNHs09DFn9vyqCPr3aZ00=,iv:PsWNYQDIYD5FtinWlHBR4gzR2nGk4sA+RfvH6MZvKUs=,tag:XQBCzcIvOB13zk4+drNxXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
