---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
components:
  - ../../components/common
resources:
  - ./home-assistant/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  # - ./node-red/ks.yaml
