---
apiVersion: v1
kind: Service
metadata:
  name: traefik-public
  namespace: networking
  annotations:
    io.cilium/lb-ipam-ips: "192.168.42.66"
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.42.66"
  selector:
    app.kubernetes.io/instance: traefik-networking
    app.kubernetes.io/name: traefik
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-pub
  - name: https
    port: 443
    protocol: TCP
    targetPort: https-pub
