apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:JCwP1JJv9eVH3b6JvJGenuFuGiYFKm2cqzPiiRxPjvM3RiiBUhq9LA==,iv:dlkEoTzWKpW4Lp6MDHP3Pm17Zr+SnmGFwG3/Ug4hp0c=,tag:skvUf+RV/bq3lP1EiWi5gQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gekefns4nyh2xrkwgll67yt232gl0gndkuq0xrvd8clsjt2gzeas2zryhg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMnE3amNvMlY5K0dJZlUx
            L3pGNHFOWmVYOTlURlphMHNaVGVreFBGY0FvClZMVDYrblFzcVpWZHdJblFieml6
            VWJVay9taElEeGV4TWhCZzBZNjBiRk0KLS0tIEJ3WmpIQ2tRcFk2aUZTOExrTUZn
            Szl5QTY0eHFsdWhjbFJFMVJXekVVYTQKd9m6rlUh1OBAbbhqBwzCgZirxKtoejaS
            3P6eR/hc9ibBpWOX6DwjXdzyvDUcux8eKIzwB6jCmbhNHGjhvYSELg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T13:22:33Z"
    mac: ENC[AES256_GCM,data:JnDQrqQosB7+hShHPcrlDDRFhih0qmOcsw+zSDAmw4RJr7L1NQeWs2bhuSi/UXILTPOzWTS22/95LBj0pg6dXI2F1hXBF6d/2BpONe3dHGsR4AiZRWdoS+C1AdGutyEct7QKIozYHK0TflHrknpVhFFx0pGvWRpH454ZMxxcxhw=,iv:CEg6u8tyZUX7EglGizbnzBk2c5p5PJAlksu2jmHCdRU=,tag:fc5i9x0K/gSStUKNtN6Q7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
