---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-exp-config
  namespace: gaming
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-exp-data
  namespace: gaming
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
