---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prowlarr
  namespace: flux-system
spec:
  targetNamespace: media
  path: ./kubernetes/apps/media/prowlarr/app
  prune: false
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
