---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: flaresolverr/flaresolverr
              tag: v3.3.14
            env:
              TZ: Europe/Paris
            resources:
              requests:
                memory: 105Mi
              limits:
                memory: 512Mi
    service:
      main:
        ports:
          http:
            port: 8191
