---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    controllers:
      mosquitto:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-config:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.18
              pullPolicy: IfNotPresent
            command: ["/bin/sh", "-c"]
            args: ["cp /data/mosquitto_secret/* /data/external_config/ && mosquitto_passwd -U /data/external_config/mosquitto_pwd"]
        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.18
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 150Mi
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: mosquitto
        ports:
          http:
            port: 80
          mqtt:
            port: 1883
    persistence:
      config:
        existingClaim: mosquitto-config
        advancedMounts:
          mosquitto:
            app:
              - path: /data
      config-file:
        type: configMap
        name: mosquitto-configmap # overriden by kustomizeconfig
        advancedMounts:
          mosquitto:
            app:
              - path: /mosquitto/config/mosquitto.conf
                subPath: mosquitto.conf
      secret-file:
        type: secret
        name: mosquitto
        defaultMode: 0700
        advancedMounts:
          mosquitto:
            init-config:
              - path: /data/mosquitto_secret
      external-config:
        enabled: true
        type: emptyDir
        advancedMounts:
          mosquitto:
            app:
              - path: /mosquitto/external_config
            init-config:
              - path: /data/external_config
