---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./helmrelease.yaml
  - ./mosquitto-secrets.sops.yaml
  - ./pvc.yaml
configMapGenerator:
  - name: mosquitto-configmap
    files:
      - mosquitto.conf=./config/mosquitto.conf
configurations:
  - ./patches/kustomizeconfig.yaml
