kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mosquitto
    namespace: home
stringData:
    mosquitto_pwd: ENC[AES256_GCM,data:Wdi0Cfq+3e9YqciVX/Ii8/sNMYGgMCVhyyUyMaJ7Z8HoLHYytHQZN6nHsbMERe0JEvivFOUXpVU4hOAow4+s96OyWlQm8wT3HOGWNBMcuFzs96AoT0hF5QBKdz4WXKbyCrT1GEA40I1d0Gmcm65K8tFsny8DxWFd3Egt9w==,iv:8QbCiezrThYamrta4J9zsWNXjGs87r4pN2TqsAOh/Dc=,tag:KHVrQnzQR3sz8LioXokbIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gekefns4nyh2xrkwgll67yt232gl0gndkuq0xrvd8clsjt2gzeas2zryhg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZzdwbWdkUC9uWDk4OU8w
            aDk1NndwUFdyR29BTDRnQWtoQ244NFoyTjNjClkxczZVcFJmeFArTnh5QitEZklC
            d0tLZjdFR3lYL1F3RWNVU3BjZkpKdWcKLS0tIFR5dDR3cTc4c3hjKy9UNVpGN2Vu
            ZUhYUE5FcUgybUt4QzBCYmxOc0M5dnMK59wH1xlZ43Q5KNhAYIVEfYzovpPHEJOi
            Vga8x9SUn1AaW/gW+WXE1xFpezRz4QbX+umRH4rJpjA6AfQes1EiIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T06:57:32Z"
    mac: ENC[AES256_GCM,data:eJ/4kxxa+gUwQATVHZ9qudlTN11Q4Lh+/+qeHf+gWaMqOeIYNcj8xSN/+pEN7isVZj4fvcOq+yp5dLNWbqWL+DlVdATvWLXTOuWdjoZnQGgNlcqJ805Atj43+6HvPuz9ZAD+bHixYq11vhfpso1Us21ZIQeISTbF+j7JYaMEAR4=,iv:x2wWcSctDamq5ovMkVDzj8mFuTHHcTFmbFqKlisNPmk=,tag:xzVSUeACwEbPr8x7/uWKqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
