---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-config
  namespace: home
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-80d03813-e6ab-4533-bea0-291f68fdbd7b
