apiVersion: v1
kind: Secret
metadata:
    name: pod-gateway-vpnconfig
    namespace: vpn
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:xcFgxyxcEws4PxENyiRCF1tlmlqX19msQ0DB57qmJVP8pxT2Y9zRfb9cYGY=,iv:b//hK93/mOePBh/kS5tCjecshvoqiAFkrnyVklaGHww=,tag:ZvwWYGqomsMxL3KzFQZF5w==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:JPg5TXEYPFt7upTlDFOf2i/cFVB/5GGFnVwbmQS1+gXG+cl9CE2FlBNlsFU=,iv:G3M0Xw9/z57H1g6ZGGxxHxowzLFxfdfRiRgZkF/WgD4=,tag:2bEIKooQVXjLIeNeuvrLow==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:BHagY2sBHZjtfPc=,iv:STuHC8BaODxaR2620Nx2/boTQA/BQumdcREB1k01r0E=,tag:4VMycZuGX4/kNVYInVAYdw==,type:str]
    WIREGUARD_DNS: ENC[AES256_GCM,data:oP7WLDI4Irk=,iv:URkFnr2GkCMNP3gcTBSDnUHwBCyiwG0XoY9asDmaeAY=,tag:RXs78Ss1chG31syTvw2JIg==,type:str]
    VPN_ENDPOINT_IP: ENC[AES256_GCM,data:zO5RBNIzqz9tKJYVHw==,iv:2x2LbY1yVxr9F4AAhlg91WVovecSmJvgHbleliGHkVw=,tag:6sdeeSbb0VMkAtxU7+FkKQ==,type:str]
    OPENVPN_USER: ENC[AES256_GCM,data:4XhrO4OIvh5fAJaQAjSloQ==,iv:5LPUe2ql1d9mSNI+06lNUJnFKpEnItLCnAF0urPxVZ4=,tag:chRJMd61zMyChAKVE+ThCQ==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:wq9e95xWdKbar++9q+mMSNozghAFcgT4UaGnSsJY+zU=,iv:bSNiDcBT3l7/G1Bj7wKpU6Os+TXUd51iWpTMRlkERZY=,tag:G3Rv5G3oARuEqWODxtD7qw==,type:str]
    #ENC[AES256_GCM,data:TjbsNRK894CPGyCzNDN/AC1JMz79HYZGEaBAiLI2IMy3,iv:/IVWJ0i+B0pKLmZD8hKC9l+ZXM/gVeTLzWlfDAfrJe8=,tag:sMOP0hUq1YiO8z0Vriz/Cw==,type:comment]
    #ENC[AES256_GCM,data:27khryxNlC3dRy/dtjJv2hdm5q3uJ6BTKQ==,iv:2cg1wJ2ZxXrOUJBmK97RakVN32O5qY0wYq38qPf47u0=,tag:8dmpjnJ3e+Clqe0s6JBqpQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gekefns4nyh2xrkwgll67yt232gl0gndkuq0xrvd8clsjt2gzeas2zryhg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTEhPRGtOZ3Z3WU1jMTUw
            OFRWSVBHU1I4a0laKzBSMXR6c1FzMldTVVFvCmtDTC9ZMnNlMjlWTWkrTTgvWEVa
            SkFWdzdrd25QMlF6WmZ5RE04YjRYUjQKLS0tIGFGb3JuWDdkeWV4bXd4Njd5Z0RF
            cGhzclQ2cU1CTzlqQkFZU3RUdVd3SlUKhJ0Pxl0ysaJ9DHALD8pVlsmie+S0GNVt
            Qr+7NgBXBXvg+6K5zwL7zqXlSy3VXbhNoHhpZRrGYcfHkVjfYbX2Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-08T08:17:17Z"
    mac: ENC[AES256_GCM,data:Mlzc734JuU0+hqkksap95jFpTKR6A03jfXV+x6FZtPNeEIVyC+4gEL0KYHiZcw4Dwa4UsKiUBUwsKViesl9RZ07Rn8fOhYoDbu+YGI7K5xe/Kk2P3mqf7VRqqP56sguRJlUHMtHKO/ubYKAA65nAuDXXtlY5WaqqnIABOHD1e0Y=,iv:0Vxfctfg/vsOB7AX9mGV2+w6OfHmzYh6IIEWV11Guck=,tag:o1O1VHNxtnRRvcixnMKc1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
