---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-node-red
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-7805877c-42bd-41fc-9038-70aab02a028c
