# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: influxdb-auth
    namespace: databases
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:DgLoljeh+FWp5Anr7a6e9K57smpSJjHd,iv:oqEEK8zlZU2KwHytDXIfWgHZtZmdjHCg2aEoxh7h9g0=,tag:CyNSKHqMUBsI+n9xrwb5Bw==,type:str]
    admin-token: ENC[AES256_GCM,data:6mUVA+T3/56yMrE9h3lDe9JQGk7wL42GnVyvP1GebRY=,iv:0CBhWqxGVVQWCfkUWScJ8ZR/VFGF/aGQ4LSDNrfk+wA=,tag:tnRcisE6IDZ/1WxscVxC2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gekefns4nyh2xrkwgll67yt232gl0gndkuq0xrvd8clsjt2gzeas2zryhg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQm9mNWFLeUtuTlJhbTVT
            VjlTMGg2azhnSkduMDl3bS9naWNxZFJkakZJCkV5NjV1UGJwS1ZPdUdBMlhvYU1B
            SXlhRUk5UHFyalJNZFN3SDZaMGlhZ0EKLS0tIEorRURLUS85MkhoWk9GeTY4RVNs
            bW9zci95MllYcERna0VYQUpVV3lYNkUKMYI3J3lV2BpVEmFAyhEQuHH9AVyFEM/U
            QViWxoAEakQoBpMrL2HnnObEwu7SgS95crDuGw4OeSt8swFtu9rxtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-27T11:53:51Z"
    mac: ENC[AES256_GCM,data:e3UDv/jITNhrQyrZcAIp9X+ZCQlKDfVfAH2y3Vfz06vONUNUowEpm4Hji7AAlkSm/IlUy4qgI9OFEnKgMb2au4w3rrAZMJM5aWi2PgJYPehoxTAPxaB/kos83AxNE+7BnhIiqC5GJhPa2eXWyh5mwvEN0uq2b/nJEZ2FM9UbH0Q=,iv:9vibITEZkArZ64MGgvoFeQp+KtDfMQnV5J1PlQlQkIU=,tag:NBxkzNuCEhFHdMunh58I6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
