---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 28.3.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    deployment:
      replicas: 2
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/instance
              operator: In
              values:
              - traefik
          topologyKey: kubernetes.io/hostname
    service:
      enabled: true
      annotations:
        io.cilium/lb-ipam-ips: "192.168.42.65"
      spec:
        loadBalancerIP: "192.168.42.65"
    ports:
      web:
        port: 8000
        expose:
          default: true
        redirectTo:
          port: websecure
      websecure:
        port: 8443
        expose:
          default: true
      http-pub:
        port: 7080
        redirectTo:
          port: https-pub
      https-pub:
        port: 7443
      metrics:
        port: 9100
        expose:
          default: false
    ingressRoute:
      dashboard:
        enabled: false
        tlsOptions:
    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        sniStrict: true
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true

    # additionalArguments:
    #   - '--entryPoints.web.http.redirections.entryPoint.to=websecure'
    #   - '--entryPoints.web.http.redirections.entryPoint.scheme=https'
    #   - '--entrypoints.web.http.redirections.entryPoint.to=:443'
    #   - '--entryPoints.http-pub.http.redirections.entryPoint.to=https-pub'
    #   - '--entryPoints.http-pub.http.redirections.entryPoint.scheme=https'
    #   - '--entrypoints.http-pub.http.redirections.entryPoint.to=:443'
