---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Paris"
  COREDNS_ADDR: "10.43.0.10"
  KUBE_VIP_ADDR: "192.168.42.32"
  CLUSTER_CIDR: "10.69.0.0/16"
  SERVICE_CIDR: "10.96.0.0/16"
  CILIUM_POOL_CIDR: "192.168.42.64/27"
