apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:pqyg1wZMf/Fsml/doJdce3kAk7Bv2lGtDP9h07QIgY0=,iv:Q6u1aMbal/cQV2K6z+UZ7mAt59K/RfLOkRBUWGPuj48=,tag:JQvk76kS3Oku4M0d/6Lu6g==,type:str]
    SONARR__API_KEY: ENC[AES256_GCM,data:5nAZpGPlZTa+w6qlC1Z+47ZbuZKA5ZWEnqCTxDcVo3I=,iv:IJuiFWJNQUvrVBZmq5JKL5351Uw9kxBebfniSyLZLtA=,tag:a2O2Ww3UVdJdWfj9gPo/Zg==,type:str]
    PROWLARR__API_KEY: ENC[AES256_GCM,data:ZvmRO5hoqL6BeyFPTPckV2m8qqe1wjwpUn3lCTo/6Zs=,iv:+QwyaWulkKk2e0ofN7PlHkxanyAQ0tTma3UrOyNWJPY=,tag:7eci72KUACEwLfG2LowMfg==,type:str]
    SECRET_MOSQUITTO__USERNAME: ENC[AES256_GCM,data:a1dyyw2zY+9f49k=,iv:WGQ4kCC5fSkTs9jCqiM5YzSBZNmRZTUIheqtsx/vyPw=,tag:4ywnFBvjj/MWiX7AtyuOdA==,type:str]
    SECRET_MOSQUITTO__PASSWORD: ENC[AES256_GCM,data:r1V02Q+1gLHANh7Jd3nvf3xmRAFzeqqJ,iv:tNGKIZS9dYkd5f1KLLXBjHj0zCFh0Y01OuDNxhHCJys=,tag:zFGdbCDw8D/Rq9IdckPb3Q==,type:str]
    SECRET_WEB_CABINET_DOMAIN: ENC[AES256_GCM,data:jTXACmfoNU+uneYOjys=,iv:ejd6L0tSpOtcGyo1PQy7bv7ppOEaRJBhb9nItYinFB0=,tag:t/wbXrTY2qTQJnynKoRqPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gekefns4nyh2xrkwgll67yt232gl0gndkuq0xrvd8clsjt2gzeas2zryhg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscmlGSlpTRTljamI3MXVw
            Wk5DcEFjZkhTU2VSWjRlTExRVmEyTk1FY3dnCnhjNmdkUE1nTWNFNFpSY3A0ckdx
            MHBHL0h1bHlIbkgvcVdHVHFSWGQ5WTQKLS0tIDFqeEw5OHZ1UjlNUzBGa0R5cWNl
            dVJOUzN4UERGdlVzYmR2blc1OENOMlkK9lUDnikL9iO+dxiRNq3SmZZ03T4BI/Vq
            7ghSimo7w4Kmks1fNe/3Sp6/aFTTeHwh4pHPZYrNmhA1OuGLMQaecA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-07T05:28:59Z"
    mac: ENC[AES256_GCM,data:HeM850+Ffpe6Ql71EDU73pxaYm5Z1xdeSJjNCQzXwYwHwJhpqZuAIJe7nPPHkgo6g0PFoO0wAWQL4qW3o+IMhQ1Mv//a2ZjK0DB5DZ5z4zb2mOHaCyPNY5BM1Lr75fWpPHBnu3mvRiz2FPgEQOiVQ//Qc1zT2yaEVkZtCjwo7Rk=,iv:tm992yZmxCTw4Pg3fw/N2pHpx4IfaNB3bQdMisCVFEA=,tag:kKcgmLssi7DVGxfY3IE/Kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
