---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-traefik-certificates
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/traefik/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: cluster-apps-cert-manager-issuers
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-traefik
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/traefik/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-traefik-middlewares
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-traefik
  path: ./kubernetes/apps/networking/traefik/middlewares
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-traefik-ingress-routes
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-traefik
    - name: cluster-apps-traefik-middlewares
  path: ./kubernetes/apps/networking/traefik/ingressroutes
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-traefik-hajimari
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-hajimari
  path: ./kubernetes/apps/networking/traefik/hajimari
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
