---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: amd-device-plugin
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.15.1
      sourceRef:
        kind: HelmRepository
        name: amd-device-plugin
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    nfd:
      enabled: true
    dp:
      image:
        repository: docker.io/rocm/k8s-device-plugin
        tag: 1.25.2.7
    node_selector:
      kubernetes.io/arch: amd64
      gpu/amd: "true"
