---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tautulli
  namespace: flux-system
spec:
  targetNamespace: media
  path: ./kubernetes/apps/media/tautulli/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
