---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gecko-ninja
spec:
  secretName: gecko-ninja-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: ${SECRET_DOMAIN}
  dnsNames: ["${SECRET_DOMAIN}", "*.${SECRET_DOMAIN}"]
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cabinet-piet
spec:
  secretName: cabinet-piet-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: ${SECRET_DOMAIN_WEB_CABINET}
  dnsNames: ["${SECRET_DOMAIN_WEB_CABINET}", "*.${SECRET_DOMAIN_WEB_CABINET}"]
